# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

OrdererOrgs:
  - Name: Orderer
    Domain: bookandblock.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.bookandblock.com
    EnableNodeOUs: true
    Template:
      Count: 3
# Custom, iterated values are possible
# Start: 10
# Hostname: {{.Prefix}}{{.Index}}
    Users:
      Count: 1
