# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  booknetwork:

services:
  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=bookandblock
      - COUCHDB_PASSWORD=bookandblock
    #Port mapping should be used in testing environments, not in productional environments
    ports:
      - "5984:5984"
    networks:
      - booknetwork

  peer0.org1.bookandblock.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=bookandblock
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=bookandblock
    depends_on:
      - couchdb0

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=bookandblock
      - COUCHDB_PASSWORD=bookandblock
    ports:
      - "6984:5984"
    networks:
      - booknetwork

  peer1.org1.bookandblock.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=bookandblock
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=bookandblock
    depends_on:
      - couchdb1

  couchdb2:
    container_name: couchdb2
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=bookandblock
      - COUCHDB_PASSWORD=bookandblock
    ports:
      - "7984:5984"
    networks:
      - booknetwork

  peer2.org1.bookandblock.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=bookandblock
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=bookandblock
    depends_on:
      - couchdb2
