# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  ca.bookandblock.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.bookandblock.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.bookandblock.com-cert.pem
# adjust this value in order to prevent failure on server startup
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/STRING_TO_REPLACE
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b bookandblock:bookandblockpassword -d'
    volumes:
      - ../crypto-config/peerOrganizations/org1.bookandblock.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.bookandblock.com
    networks:
      - booknetwork

  orderer.bookandblock.com:
    container_name: orderer.bookandblock.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererBookAndBlock
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/genesis.block
    - ../crypto-config/ordererOrganizations/bookandblock.com/orderers/orderer.bookandblock.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/bookandblock.com/orderers/orderer.bookandblock.com/tls/:/var/hyperledger/orderer/tls
    - orderer.bookandblock.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.org1.bookandblock.com:
    container_name: peer0.org1.bookandblock.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.bookandblock.com
      - CORE_PEER_ADDRESS=peer0.org1.bookandblock.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.bookandblock.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.bookandblock.com:7051
      - CORE_PEER_LOCALMSPID=OrgBookAndBlock
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.bookandblock.com/peers/peer0.org1.bookandblock.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.bookandblock.com/peers/peer0.org1.bookandblock.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.bookandblock.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.org1.bookandblock.com:
    container_name: peer1.org1.bookandblock.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.bookandblock.com
      - CORE_PEER_ADDRESS=peer1.org1.bookandblock.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.bookandblock.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.org1.bookandblock.com:7051
      - CORE_PEER_LOCALMSPID=OrgBookAndBlock
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.bookandblock.com/peers/peer1.org1.bookandblock.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.bookandblock.com/peers/peer1.org1.bookandblock.com/tls:/etc/hyperledger/fabric/tls
        - peer1.org1.bookandblock.com:/var/hyperledger/production
    ports:
      - 8051:7051
      - 8053:7053

  peer2.org1.bookandblock.com:
    container_name: peer2.org1.bookandblock.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.org1.bookandblock.com
      - CORE_PEER_ADDRESS=peer2.org1.bookandblock.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.bookandblock.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.bookandblock.com:7051
      - CORE_PEER_LOCALMSPID=OrgBookAndBlock
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.bookandblock.com/peers/peer2.org1.bookandblock.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.bookandblock.com/peers/peer2.org1.bookandblock.com/tls:/etc/hyperledger/fabric/tls
        - peer2.org1.bookandblock.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053
